version: '3.9'

services:
  hack_database:
    container_name: hack_database
    image: amd64/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - store-volume-db:/var/lib/postgresql/data

  adminer:
    image: amd64/adminer:latest
    container_name: hack_adminer
    environment:
      ADMINER_DEFAULT_SERVER: hack_database
    restart: always
    ports:
      - 8080:8080

volumes:
  store-volume-db:
